dist: bionic

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27,py2-bench
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39,py3-bench
    - python: pypy3
      env: TOXENV=pypy3,pypy3-bench
    - python: 3.9
      env: TOXENV=lint,docs
      install:
        - pip install tox
      script:
        - tox

install:
    - pip install tox coveralls

script:
    - tox
    - coveralls
